/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の情報を取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分の取引履歴を取得 */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Transaction"][];
                            /** @description 次のページを取得するためのカーソル */
                            next_cursor?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/bills/{bill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 請求の詳細を取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bill_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bill"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/bills/{bill_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 請求を承認して支払いを実行する
         * @description 成功した場合、プロジェクトが指定したリダイレクトURLを返す
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bill_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 支払い完了 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            redirect_url?: string;
                        };
                    };
                };
                /** @description 残高不足など */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 既に処理済み */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/bills/{bill_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 請求を拒否する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bill_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 拒否完了 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 既に処理済み */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自分がオーナーまたは管理者のプロジェクト一覧 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全ユーザー一覧を取得 */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["User"][];
                            /** @description 次のページを取得するためのカーソル (存在しない場合は未設定) */
                            next_cursor?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 指定したカテゴリのランキングを取得
         * @description 指定されたカテゴリに基づいたユーザーランキングを返します
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path: {
                    /**
                     * @description ランキングの集計種別
                     *     - balance: 現在の所持金残高順
                     */
                    category: "balance";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["User"][];
                            /** @description 次のページを取得するためのカーソル (存在しない場合は未設定) */
                            next_cursor?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全プロジェクト一覧を取得 */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Project"][];
                            /** @description 次のページを取得するためのカーソル */
                            next_cursor?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /** プロジェクトを新規作成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プロジェクト詳細 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** プロジェクト管理者一覧を取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"][];
                    };
                };
            };
        };
        put?: never;
        /** プロジェクト管理者を追加 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        user_id: string;
                    };
                };
            };
            responses: {
                /** @description Added */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/admins/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** プロジェクト管理者を削除 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** APIクライアント一覧 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIClient"][];
                    };
                };
            };
        };
        put?: never;
        /** APIクライアントを新規発行 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created (Secretはここでしか表示しない) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIClient"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** APIクライアントを削除（無効化） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    project_id: string;
                    client_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description ユーザー */
        User: {
            /** Format: uuid */
            id?: string;
            /** @description traP ID */
            name?: string;
            /**
             * Format: int64
             * @description 現在の残高
             */
            balance?: number;
        };
        /** @description プロジェクト */
        Project: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: uuid */
            owner_id?: string;
            /** @description プロジェクト管理者のユーザーID一覧 */
            admin_ids?: string[];
            /** Format: int64 */
            balance?: number;
        };
        /** @description 完了した取引 */
        Transaction: {
            /** Format: uuid */
            id?: string;
            /**
             * @description 取引の種類
             *     - TRANSFER: プロジェクトからユーザーへの送金 (Project -> User)
             *     - BILL_PAYMENT: プロジェクトへの請求の支払い (User -> Project)
             * @enum {string}
             */
            type?: "TRANSFER" | "BILL_PAYMENT";
            /** Format: int64 */
            amount?: number;
            /** Format: uuid */
            project_id?: string;
            /** Format: uuid */
            user_id?: string;
            description?: string;
            /** Format: date-time */
            created_at?: string;
        };
        /** @description 請求 */
        Bill: {
            /** Format: uuid */
            id?: string;
            /** Format: int64 */
            amount?: number;
            /**
             * Format: uuid
             * @description 請求対象のユーザーID
             */
            user_id?: string;
            description?: string;
            /** Format: uuid */
            project_id?: string;
            /** @enum {string} */
            status?: "PENDING" | "COMPLETED" | "REJECTED" | "FAILED";
            /** Format: date-time */
            created_at?: string;
        };
        /** @description APIクライアント */
        APIClient: {
            client_id?: string;
            /** @description 作成時のみ返却される */
            client_secret?: string;
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
