/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 自プロジェクトの情報を取得 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Project"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/project/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取引履歴を取得 */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Transaction"][];
                            /** @description 次のページを取得するためのカーソル (存在しない場合は未設定) */
                            next_cursor?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ユーザーへ送金する (配布・賞与など) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTransactionRequest"];
                };
            };
            responses: {
                /** @description 送金成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Transaction"];
                    };
                };
                /** @description 残高不足など */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ユーザーへの請求を作成する
         * @description レスポンスに含まれる payment_url へユーザーを誘導してください
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBillRequest"];
                };
            };
            responses: {
                /** @description 請求作成完了 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateBillResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bills/{bill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 請求のステータスを確認する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    bill_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Bill"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Project: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: int64 */
            balance?: number;
        };
        Transaction: {
            /** Format: uuid */
            id?: string;
            /** Format: int64 */
            amount?: number;
            /**
             * @description 取引の種類
             *     - TRANSFER: プロジェクトからユーザーへの送金 (Project -> User)
             *     - BILL_PAYMENT: プロジェクトへの請求の支払い (User -> Project)
             * @enum {string}
             */
            type?: "TRANSFER" | "BILL_PAYMENT";
            /**
             * Format: uuid
             * @description 取引相手のユーザーID (UUID)
             */
            user_id?: string;
            /** @description 取引相手のユーザー名 (traP ID) */
            user_name?: string;
            /** Format: uuid */
            project_id?: string;
            description?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Bill: {
            /** Format: uuid */
            id?: string;
            /** Format: int64 */
            amount?: number;
            /**
             * Format: uuid
             * @description 請求対象のユーザーID (UUID)
             */
            user_id?: string;
            /** @description 請求対象のユーザー名 (traP ID) */
            user_name?: string;
            description?: string;
            /** @enum {string} */
            status?: "PENDING" | "COMPLETED" | "REJECTED" | "FAILED";
            /** Format: date-time */
            created_at?: string;
        };
        CreateTransactionRequest: {
            /** @description 送金先のユーザー名 (traP ID) */
            to_user: string;
            /** Format: int64 */
            amount: number;
            description?: string;
            /**
             * Format: uuid
             * @description 冪等性キー (必須推奨)
             */
            request_id?: string;
        };
        CreateBillRequest: {
            /** @description 請求先のユーザー名 (traP ID) */
            target_user: string;
            /** Format: int64 */
            amount: number;
            description?: string;
            /**
             * Format: uri
             * @description 決済成功時のリダイレクト先URL
             */
            success_url: string;
            /**
             * Format: uri
             * @description 決済キャンセル/拒否時のリダイレクト先URL
             */
            cancel_url: string;
        };
        CreateBillResponse: {
            /** Format: uuid */
            bill_id?: string;
            /**
             * Format: uri
             * @description ユーザーをリダイレクトさせる決済確認ページのURL
             */
            payment_url?: string;
            /** Format: date-time */
            expires_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
